version: 1.0.8.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - gh-pages
image: Visual Studio 2017
configuration:
- Release
- Debug
environment:
  gp_build_user: ObsidianMinor
  gp_build_user_email: obsidianminor@gmail.com
  access_token:
    secure: hbO0PhmlEaYZiDRbliEBxSbB8qQBnE0e4XxRvW7GhLRdlYO5/CGwbsaMgUBMov1N
build:
  verbosity: minimal
test_script:
- ps: dotnet test tests/Gfycat.Net.Tests/Gfycat.Net.Tests.csproj
artifacts:
- path: '**/*$(APPVEYOR_BUILD_VERSION)*.nupkg'
  name: Nuget Packages
deploy:
- provider: NuGet
  api_key:
    secure: lIIha19su56DoSb9z5LilA8cIKhNsph/NqxUxIYdh+4XJq67ZRt+1Fkohqx8RHh0
  artifact: /.*\.nupkg/
  on:
    branch: master
