environment:
  gp_build_user: ObsidianMinor
  gp_build_user_email: obsidianminor@gmail.com
  access_token:
    secure: 23ed162/PauWQ9VQ2cLGaJljAGKQbUMV9IJfBMOm1y+IrVJkZ4zIMF4GB/er3Bb5

version: 1.0.7.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
image: Visual Studio 2017
build:
  verbosity: minimal

before_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            cinst docfx -y
        }

build_script:
  - ps: |
        nuget restore Gfycat.Net.sln
        dotnet build Gfycat.Net.sln

after_build:
- ps: |
      if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
      {
          docfx docs/docfx.json
          git config --global credential.helper store
          Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
          git config --global user.email $env:gp_build_user_email
          git config --global user.name $env:gp_build_user

          git clone https://github.com/ObsidianMinor/Gfycat.Net.git -b gh-pages origin_site -q
          Copy-Item origin_site/.git _site -recurse
          CD _site
          git add -A 2>&1
          git commit -m "CI Updates" -q
          git push origin gh-pages -q
      }

test_script:
- ps: |
      
