environment:
  gp_build_user: ObsidianMinor
  gp_build_user_email: obsidianminor@gmail.com
  access_token:
    secure: 23ed162/PauWQ9VQ2cLGaJljAGKQbUMV9IJfBMOm1y+IrVJkZ4zIMF4GB/er3Bb5

pull_requests:
  do_not_increment_build_number: true

version: 1.0.8.{build}
skip_tags: true

image: Visual Studio 2017

artifacts:
  - path: '**/*$(APPVEYOR_BUILD_VERSION)*.nupkg'
    name: Nuget Packages

before_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            cinst docfx -y
        }
        appveyor-retry dotnet restore Gfycat.Net.sln

build_script:
  - ps: |
          dotnet build Gfycat.Net.sln --configuration %CONFIGURATION% /p:Version=$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH

after_build:
- ps: |
      if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
      {
          CD docs
          docfx docfx.json
          git config --global credential.helper store
          Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
          git config --global user.email $env:gp_build_user_email
          git config --global user.name $env:gp_build_user

          git clone https://github.com/ObsidianMinor/Gfycat.Net.git -b gh-pages origin_site
          Copy-Item origin_site/.git _site -recurse
          CD _site
          git add .
          git commit -m "CI Updates"
          git push origin gh-pages
          CD ..\..
      }

test_script:
- ps: |
      dotnet test tests/Gfycat.Net.Tests/Gfycat.Net.Tests.csproj


deploy:
  provider: NuGet
  name: nugetmain
  api_key:
    secure: 3iXTugTMw5kRARtHywAtSsM6+AHLO8CQ4IoKrDXkgqeeHzjhz3bopc0FLckjOPk3
  artifact: /.*\.nupkg/
  on:
    branch: master

-
  branches:
  only:
      - master
      - dev

  configuration: Release
-
  configuration: Debug
